/**
 * DoneHub channel types at the pinned upstream contract.
 * @see https://github.com/deanxv/done-hub/blob/1c09e7d75dc170a53d47af1e88c498816a5b85fb/web/src/constants/ChannelConstants.js
 */
export const DoneHubChannelType = {
  OpenAI: 1,
  AzureOpenAI: 3,
  Custom: 8,
  PaLM2: 11,
  Anthropic: 14,
  Baidu: 15,
  Zhipu: 16,
  Ali: 17,
  Xunfei: 18,
  Ai360: 19,
  OpenRouter: 20,
  TencentLegacy: 23,
  AzureSpeech: 24,
  Gemini: 25,
  Baichuan: 26,
  MiniMax: 27,
  DeepSeek: 28,
  Moonshot: 29,
  Mistral: 30,
  Groq: 31,
  AmazonBedrock: 32,
  LingYiWanWu: 33,
  Midjourney: 34,
  Cloudflare: 35,
  Cohere: 36,
  StabilityAI: 37,
  Coze: 38,
  Ollama: 39,
  Tencent: 40,
  Suno: 41,
  VertexAI: 42,
  SiliconFlow: 45,
  Jina: 47,
  GitHubModels: 49,
  RecraftAI: 51,
  Replicate: 52,
  Kling: 53,
  AzureDatabricks: 54,
  AzureOpenAIV1: 55,
  XAI: 56,
  GeminiCli: 57,
  ClaudeCode: 58,
  Codex: 59,
  Antigravity: 60,
  VertexAIExpress: 61,
  AmazonBedrockMessages: 62,
} as const

export type DoneHubChannelType =
  (typeof DoneHubChannelType)[keyof typeof DoneHubChannelType]

export const DoneHubChannelTypeNames = {
  [DoneHubChannelType.OpenAI]: "OpenAI",
  [DoneHubChannelType.AzureOpenAI]: "Azure OpenAI",
  [DoneHubChannelType.Custom]: "Custom",
  [DoneHubChannelType.PaLM2]: "Google PaLM2",
  [DoneHubChannelType.Anthropic]: "Anthropic Claude",
  [DoneHubChannelType.Baidu]: "Baidu Wenxin",
  [DoneHubChannelType.Zhipu]: "Zhipu ChatGLM",
  [DoneHubChannelType.Ali]: "Alibaba Qwen",
  [DoneHubChannelType.Xunfei]: "iFlytek Spark",
  [DoneHubChannelType.Ai360]: "360 Brain",
  [DoneHubChannelType.OpenRouter]: "OpenRouter",
  [DoneHubChannelType.TencentLegacy]: "Tencent Hunyuan (legacy)",
  [DoneHubChannelType.AzureSpeech]: "Azure Speech",
  [DoneHubChannelType.Gemini]: "Google Gemini",
  [DoneHubChannelType.Baichuan]: "Baichuan",
  [DoneHubChannelType.MiniMax]: "MiniMax",
  [DoneHubChannelType.DeepSeek]: "DeepSeek",
  [DoneHubChannelType.Moonshot]: "Moonshot",
  [DoneHubChannelType.Mistral]: "Mistral",
  [DoneHubChannelType.Groq]: "Groq",
  [DoneHubChannelType.AmazonBedrock]: "Amazon Bedrock",
  [DoneHubChannelType.LingYiWanWu]: "01.AI",
  [DoneHubChannelType.Midjourney]: "Midjourney",
  [DoneHubChannelType.Cloudflare]: "Cloudflare AI",
  [DoneHubChannelType.Cohere]: "Cohere",
  [DoneHubChannelType.StabilityAI]: "Stability AI",
  [DoneHubChannelType.Coze]: "Coze",
  [DoneHubChannelType.Ollama]: "Ollama",
  [DoneHubChannelType.Tencent]: "Tencent Hunyuan",
  [DoneHubChannelType.Suno]: "Suno",
  [DoneHubChannelType.VertexAI]: "Vertex AI",
  [DoneHubChannelType.SiliconFlow]: "SiliconFlow",
  [DoneHubChannelType.Jina]: "Jina",
  [DoneHubChannelType.GitHubModels]: "GitHub Models",
  [DoneHubChannelType.RecraftAI]: "Recraft AI",
  [DoneHubChannelType.Replicate]: "Replicate",
  [DoneHubChannelType.Kling]: "Kling",
  [DoneHubChannelType.AzureDatabricks]: "Azure Databricks",
  [DoneHubChannelType.AzureOpenAIV1]: "Azure OpenAI V1",
  [DoneHubChannelType.XAI]: "xAI",
  [DoneHubChannelType.GeminiCli]: "Gemini CLI",
  [DoneHubChannelType.ClaudeCode]: "Claude Code",
  [DoneHubChannelType.Codex]: "Codex",
  [DoneHubChannelType.Antigravity]: "Antigravity",
  [DoneHubChannelType.VertexAIExpress]: "Vertex AI Express",
  [DoneHubChannelType.AmazonBedrockMessages]: "Amazon Bedrock (Messages)",
} as const satisfies Record<DoneHubChannelType, string>

export const DoneHubChannelTypeOptions = Object.entries(
  DoneHubChannelTypeNames,
).map(([value, label]) => ({
  value: Number(value) as DoneHubChannelType,
  label,
}))

export const DONE_HUB_MANAGED_RESOURCE_FIELD_IDS = {
  Id: "doneHub.id",
  Name: "doneHub.name",
  Type: "doneHub.type",
  Status: "doneHub.status",
  BaseUrl: "doneHub.baseUrl",
  Key: "doneHub.key",
  Models: "doneHub.models",
  ModelCount: "doneHub.modelCount",
  Groups: "doneHub.groups",
  Priority: "doneHub.priority",
  Weight: "doneHub.weight",
} as const

export const DONE_HUB_MANAGED_RESOURCE_TABLE_FIELD_IDS = [
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Id,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Name,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Type,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.BaseUrl,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.ModelCount,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Groups,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Status,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Priority,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Weight,
] as const

export const DONE_HUB_MANAGED_RESOURCE_DETAIL_FIELD_IDS = [
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Id,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Name,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Type,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Status,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.BaseUrl,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Key,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Models,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Groups,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Priority,
  DONE_HUB_MANAGED_RESOURCE_FIELD_IDS.Weight,
] as const
