import { SETTINGS_ANCHORS } from "~/constants/settingsAnchors"
import {
  buildControlDefinition,
  buildSectionDefinition,
  DEFAULT_BREADCRUMBS,
} from "~/features/OptionsSearch/registryHelpers"
import type { OptionsSearchItemDefinition } from "~/features/OptionsSearch/types"

const SITE_ANNOUNCEMENT_BREADCRUMBS = [
  ...DEFAULT_BREADCRUMBS,
  "settings:tabs.general",
  "settings:siteAnnouncementNotifications.title",
]

const PRODUCT_ANALYTICS_BREADCRUMBS = [
  ...DEFAULT_BREADCRUMBS,
  "settings:tabs.general",
  "settings:productAnalytics.title",
]

export const generalSearchSections: OptionsSearchItemDefinition[] = [
  buildSectionDefinition(
    "section:display",
    "general",
    "general-display",
    "settings:display.title",
    200,
    { keywordKeys: ["common:actions.reset"] },
  ),
  buildSectionDefinition(
    "section:appearance",
    "general",
    SETTINGS_ANCHORS.APPEARANCE,
    "settings:theme.appearance",
    201,
    { keywordKeys: ["common:actions.reset"] },
  ),
  buildSectionDefinition(
    "section:action-click",
    "general",
    "action-click",
    "settings:actionClick.title",
    202,
    { keywordKeys: ["common:actions.reset"] },
  ),
  buildSectionDefinition(
    "section:site-announcements",
    "general",
    SETTINGS_ANCHORS.SITE_ANNOUNCEMENT_NOTIFICATIONS,
    "settings:siteAnnouncementNotifications.title",
    203,
    {
      keywordKeys: ["common:actions.reset"],
      descriptionKey: "settings:siteAnnouncementNotifications.description",
      keywords: ["announcement", "notice", "polling"],
    },
  ),
  buildSectionDefinition(
    "section:changelog",
    "general",
    "changelog-on-update",
    "settings:changelogOnUpdate.title",
    204,
    { keywordKeys: ["common:actions.reset"] },
  ),
  buildSectionDefinition(
    "section:logging",
    "general",
    "logging",
    "settings:logging.title",
    205,
    { keywordKeys: ["common:actions.reset"] },
  ),
  buildSectionDefinition(
    "section:product-analytics",
    "general",
    "product-analytics",
    "settings:productAnalytics.title",
    206,
    {
      descriptionKey: "settings:productAnalytics.description",
      keywords: ["analytics", "posthog", "privacy", "anonymous", "opt out"],
    },
  ),
  buildSectionDefinition(
    "section:danger",
    "general",
    "dangerous-zone",
    "settings:danger.title",
    207,
  ),
]

export const generalSearchControls: OptionsSearchItemDefinition[] = [
  buildControlDefinition(
    "control:appearance-font",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_FONT,
    "settings:appearance.font",
    534,
    {
      descriptionKey: "settings:appearance.fontDescription",
      keywords: [
        "font",
        "serif",
        "sans",
        "typography",
        "字体",
        "字體",
        "衬线",
        "襯線",
      ],
    },
  ),
  buildControlDefinition(
    "control:appearance-text-size",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_TEXT_SIZE,
    "settings:appearance.textSize",
    533,
    {
      descriptionKey: "settings:appearance.textSizeDescription",
      keywords: [
        "text size",
        "font size",
        "large",
        "readability",
        "文字大小",
        "字体大小",
        "字體大小",
        "字号",
        "字號",
        "大字",
        "超大",
        "読みやすさ",
      ],
    },
  ),
  buildControlDefinition(
    "control:appearance-density",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_DENSITY,
    "settings:appearance.density",
    532,
    {
      keywords: [
        "density",
        "compact",
        "comfortable",
        "spacing",
        "密度",
        "紧凑",
        "宽松",
        "間距",
        "緊湊",
        "寬鬆",
      ],
    },
  ),
  buildControlDefinition(
    "control:appearance-preset",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_PRESET,
    "settings:appearance.preset",
    529,
    {
      keywords: ["theme", "preset", "Anthropic", "主题", "配色", "暖色"],
    },
  ),
  buildControlDefinition(
    "control:appearance-color",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_COLOR,
    "settings:appearance.color",
    530,
    { keywords: ["theme", "color", "palette", "主题色", "配色"] },
  ),
  buildControlDefinition(
    "control:appearance-radius",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_RADIUS,
    "settings:appearance.radius",
    531,
    { keywords: ["radius", "corners", "rounded", "圆角"] },
  ),
  buildControlDefinition(
    "control:display-currency",
    "general",
    "display-currency-unit",
    "settings:display.currencyUnit",
    500,
    {
      descriptionKey: "settings:display.currencyDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:display.title",
      ],
      keywords: ["currency", "usd", "cny", "money"],
    },
  ),
  buildControlDefinition(
    "control:display-today-cashflow",
    "general",
    "display-today-cashflow-enabled",
    "settings:display.todayCashflowEnabled",
    501,
    {
      descriptionKey: "settings:display.todayCashflowEnabledDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:display.title",
      ],
      keywords: ["cashflow", "today", "income", "consumption"],
    },
  ),
  buildControlDefinition(
    "control:display-default-tab",
    "general",
    "display-default-tab",
    "settings:display.defaultTab",
    502,
    {
      descriptionKey: "settings:display.defaultTabDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:display.title",
      ],
      keywords: ["default", "dashboard", "total balance", "today cashflow"],
      isVisible: (context) => context.showTodayCashflow,
    },
  ),
  buildControlDefinition(
    "control:appearance-theme-mode",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_THEME_MODE,
    "settings:theme.mode",
    503,
    {
      descriptionKey: "settings:theme.selectTheme",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:theme.appearance",
      ],
      keywords: ["theme", "light", "dark", "system"],
    },
  ),
  buildControlDefinition(
    "control:appearance-language",
    "general",
    SETTINGS_ANCHORS.APPEARANCE_LANGUAGE,
    "settings:appearanceLanguage.language",
    504,
    {
      descriptionKey: "settings:appearanceLanguage.languageDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:theme.appearance",
      ],
      keywords: ["language", "locale", "i18n"],
    },
  ),
  buildControlDefinition(
    "control:action-click",
    "general",
    "action-click-behavior",
    "settings:actionClick.actionIconClickTitle",
    505,
    {
      descriptionKey: "settings:actionClick.description",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:actionClick.title",
      ],
      keywords: [
        "popup",
        "sidepanel",
        "options",
        "settings",
        "toolbar",
        "icon",
      ],
    },
  ),
  buildControlDefinition(
    "control:site-announcements-polling",
    "general",
    SETTINGS_ANCHORS.SITE_ANNOUNCEMENT_NOTIFICATIONS_ENABLED,
    "settings:siteAnnouncementNotifications.polling.enable",
    506,
    {
      descriptionKey:
        "settings:siteAnnouncementNotifications.polling.enableDesc",
      breadcrumbsKeys: SITE_ANNOUNCEMENT_BREADCRUMBS,
      keywords: ["announcement", "notice", "polling", "background check"],
    },
  ),
  buildControlDefinition(
    "control:site-announcements-interval",
    "general",
    SETTINGS_ANCHORS.SITE_ANNOUNCEMENT_NOTIFICATIONS_INTERVAL,
    "settings:siteAnnouncementNotifications.polling.interval",
    507,
    {
      descriptionKey:
        "settings:siteAnnouncementNotifications.polling.intervalDesc",
      breadcrumbsKeys: SITE_ANNOUNCEMENT_BREADCRUMBS,
      keywords: [
        "announcement",
        "notice",
        "polling interval",
        "background check interval",
        "minutes",
      ],
    },
  ),
  buildControlDefinition(
    "control:site-announcements-page",
    "general",
    SETTINGS_ANCHORS.SITE_ANNOUNCEMENT_NOTIFICATIONS_PAGE,
    "settings:siteAnnouncementNotifications.page.title",
    508,
    {
      descriptionKey: "settings:siteAnnouncementNotifications.page.description",
      breadcrumbsKeys: SITE_ANNOUNCEMENT_BREADCRUMBS,
      keywords: ["announcement", "notice", "records", "page"],
    },
  ),
  buildControlDefinition(
    "control:changelog-on-update",
    "general",
    "changelog-on-update-toggle",
    "settings:changelogOnUpdate.toggleLabel",
    509,
    {
      descriptionKey: "settings:changelogOnUpdate.toggleDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:changelogOnUpdate.title",
      ],
      keywords: ["changelog", "what's new", "update log"],
    },
  ),
  buildControlDefinition(
    "control:logging-enabled",
    "general",
    "logging-console-enabled",
    "settings:logging.consoleEnabled",
    510,
    {
      descriptionKey: "settings:logging.consoleEnabledDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:logging.title",
      ],
      keywords: ["log", "console", "debug"],
    },
  ),
  buildControlDefinition(
    "control:logging-min-level",
    "general",
    "logging-min-level",
    "settings:logging.minLevel",
    511,
    {
      descriptionKey: "settings:logging.minLevelDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:logging.title",
      ],
      keywords: ["log", "debug", "warn", "error", "info"],
    },
  ),
  buildControlDefinition(
    "control:product-analytics-enabled",
    "general",
    SETTINGS_ANCHORS.PRODUCT_ANALYTICS_ENABLED,
    "settings:productAnalytics.enableLabel",
    512,
    {
      descriptionKey: "settings:productAnalytics.enableDescription",
      breadcrumbsKeys: PRODUCT_ANALYTICS_BREADCRUMBS,
      keywords: ["analytics", "posthog", "privacy", "anonymous", "disable"],
    },
  ),
  buildControlDefinition(
    "control:danger-reset-settings",
    "general",
    "danger-reset-settings",
    "settings:danger.resetSettings",
    513,
    {
      descriptionKey: "settings:danger.resetDesc",
      breadcrumbsKeys: [
        ...DEFAULT_BREADCRUMBS,
        "settings:tabs.general",
        "settings:danger.title",
      ],
      keywords: ["danger", "reset", "reset settings", "defaults"],
    },
  ),
]
